### PR TITLE
Pull in Digital Marketplace workflow template

### PR DESCRIPTION
**Pull request by bjgill**
From https://github.com/alphagov/.github with all its history. This template is used when creating a new Digital Marketplace repo to set up CI using Github Actions.

### CODE REVIEW

**Review by phantas — CHANGES_REQUESTED** [review]
I may be wrong but I think these 3 files should be inside a directory called `workflow-templates`, if we are following the same structure as on  https://github.com/alphagov/.github.
Would you mind double checking?

**Comment by bjgill** [comment]
Oops - good catch, thanks. The directory got lost whilst I was migrating from the alphagov repo. Fixed.

**Review by phantas — APPROVED** [review]
Looks good but I haven't tested. :+1:

**Comment by bjgill** [comment]
Merged - looks to be working if I try creating a new workflow in another repo

**Pull request merged**
